apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
spec:
  selector:
    matchLabels:
      app: runner
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: runner
        tier: backend
        track: stable
    spec:
      # nodeSelector:
      #   cloud.google.com/gke-preemptible: "true"
      # tolerations:
      # - effect: NoSchedule
      #   key: task
      #   operator: Equal
      #   value: preemptive
      containers:
      - name: runner
        image: runner_rpl:local
        ports:
          - name: http
            containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          httpGet:
            path: /health
            port: 8000
      - name: worker
        image: worker_rpl:local
        env:
        - name: QUEUE_URL
          value: amqp://guest:guest@queue:5672
        - name: URL_RPL_BACKEND
          value: http://rpl-activities-api:80
        - name: QUEUE_ACTIVITIES_NAME
          value: hello
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: runner-api-key
              key: runner-api-key
        ports:
          - name: http
            containerPort: 8088
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 400Mi
